# Generated by Django 4.2.4 on 2023-08-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('TypeName', models.CharField(max_length=100)),
                ('Ram', models.IntegerField()),
                ('Weight', models.FloatField()),
                ('Touchscreen', models.IntegerField()),
                ('Ips', models.IntegerField()),
                ('ppi', models.IntegerField()),
                ('Cpu_brand', models.CharField(max_length=100)),
                ('HDD', models.IntegerField()),
                ('SSD', models.IntegerField()),
                ('Gpu_brand', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
            ],
        ),
    ]
